my_dbt_project:
  outputs:
    dev:
      dataset: raw
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /home/ghifariyadi_muhammad/airflow/service-account.json
      location: US
      method: service-account
      priority: interactive
      project: golden-centaur-440309-a9
      threads: 1
      type: bigquery
  target: dev
